[connections.snowflake]
account = "ck97467.central-india.azure"
user = "AKSHATASHUKLA"
password = "Akshata13@ASD"
warehouse = "COMPUTE_WH"
database = "REGINTEL_DB"
schema = "RAW"
role = "ACCOUNTADMIN"
